import { FoodItem, Language } from './types';

export const TRANSLATIONS = {
  en: {
    profileTitle: "Let's get to know you",
    profileSubtitle: "We need this data to calculate your BMR accurately.",
    weight: "Weight",
    height: "Height",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    activityLevel: "Activity Level",
    nextBtn: "Next: Food Preferences",
    
    prefTitle: "Rate Your Foods",
    prefSubtitle: "0 = Dislike, 6 = Strongly Like. Default is 3.",
    searchPlaceholder: "Search foods...",
    noFoodsFound: "No foods found matching",
    generateBtn: "Generate Meal Plan",
    generating: "Generative AI Thinking...",
    dislike: "Dislike",
    neutral: "Neutral",
    love: "Love",
    
    planTitle: "Your Daily Plan",
    planSubtitle: "Optimized for preferences & metabolism",
    totalCalories: "Total Calories",
    prefScore: "Preference Score",
    target: "Target",
    higherBetter: "Higher is better",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    startOver: "Start Over",
    
    headerProfile: "Profile",
    headerPref: "Food Preferences",
    headerPlan: "Smart Plan",
    saveSuccess: "Saved",
    saveError: "Failed to save",
  },
  zh: {
    profileTitle: "讓我們了解您",
    profileSubtitle: "我們需要這些數據來準確計算您的 BMR。",
    weight: "體重",
    height: "身高",
    age: "年齡",
    gender: "性別",
    male: "男性",
    female: "女性",
    activityLevel: "活動量",
    nextBtn: "下一步：食物偏好",
    
    prefTitle: "食物評分",
    prefSubtitle: "0 = 不喜歡，6 = 非常喜歡。預設為 3。",
    searchPlaceholder: "搜尋食物...",
    noFoodsFound: "找不到符合的食物",
    generateBtn: "生成飲食計劃",
    generating: "AI 正在思考中...",
    dislike: "不喜歡",
    neutral: "普通",
    love: "喜愛",
    
    planTitle: "您的每日計劃",
    planSubtitle: "根據您的偏好和代謝優化",
    totalCalories: "總卡路里",
    prefScore: "偏好分數",
    target: "目標",
    higherBetter: "越高越好",
    breakfast: "早餐",
    lunch: "午餐",
    dinner: "晚餐",
    startOver: "重新開始",
    
    headerProfile: "個人資料",
    headerPref: "食物偏好",
    headerPlan: "智能計劃",
    saveSuccess: "已儲存",
    saveError: "儲存失敗",
  }
};

export const ACTIVITY_LEVELS = [
  { value: 1.2, label: { en: 'Sedentary (Office job)', zh: '久坐 (辦公室工作)' } },
  { value: 1.375, label: { en: 'Lightly Active (1-3 days/week)', zh: '輕度活動 (每週 1-3 天)' } },
  { value: 1.55, label: { en: 'Moderately Active (3-5 days/week)', zh: '中度活動 (每週 3-5 天)' } },
  { value: 1.725, label: { en: 'Very Active (6-7 days/week)', zh: '高度活動 (每週 6-7 天)' } },
  { value: 1.9, label: { en: 'Super Active (Physical job)', zh: '極度活動 (體力勞動)' } },
];

// Complete Food Database from the provided PDF
export const INITIAL_FOOD_DATABASE: FoodItem[] = [
  { id: 1, name: "White rice (白飯)", calories: 200, preference: 3 },
  { id: 2, name: "Steamed rice (蒸飯)", calories: 200, preference: 3 },
  { id: 3, name: "Yangzhou fried rice (揚州炒飯)", calories: 600, preference: 3 },
  { id: 4, name: "Beef fried rice (牛肉炒飯)", calories: 550, preference: 3 },
  { id: 5, name: "Char siu fried rice (叉燒炒飯)", calories: 550, preference: 3 },
  { id: 6, name: "Shrimp fried rice (鮮蝦炒飯)", calories: 500, preference: 3 },
  { id: 7, name: "Chicken fried rice (雞肉炒飯)", calories: 500, preference: 3 },
  { id: 8, name: "Ham fried rice (火腿炒飯)", calories: 500, preference: 3 },
  { id: 9, name: "Pineapple fried rice (菠蘿炒飯)", calories: 550, preference: 3 },
  { id: 10, name: "Chinese sausage fried rice (臘腸炒飯)", calories: 600, preference: 3 },
  { id: 11, name: "Egg fried rice (蛋炒飯)", calories: 500, preference: 3 },
  { id: 12, name: "Luncheon meat fried rice (午餐肉炒飯)", calories: 600, preference: 3 },
  { id: 13, name: "Claypot rice with chicken & mushrooms (冬菇蒸雞飯)", calories: 500, preference: 3 },
  { id: 14, name: "Claypot rice with preserved sausage (臘腸煲仔飯)", calories: 500, preference: 3 },
  { id: 15, name: "Claypot rice with pork ribs (排骨煲仔飯)", calories: 450, preference: 3 },
  { id: 16, name: "Claypot rice with mixed preserved meats (臘味煲仔飯)", calories: 500, preference: 3 },
  { id: 17, name: "Claypot chicken rice (雞煲仔飯)", calories: 500, preference: 3 },
  { id: 18, name: "Claypot tofu rice (豆腐煲仔飯)", calories: 450, preference: 3 },
  { id: 19, name: "Sticky rice in lotus leaf (Lo Mai Gai) (糯米雞)", calories: 400, preference: 3 },
  { id: 20, name: "Mini sticky rice in lotus leaf (珍珠雞)", calories: 400, preference: 3 },
  { id: 21, name: "Steamed rice-roll with BBQ pork (叉燒腸粉)", calories: 80, preference: 3 },
  { id: 22, name: "Steamed rice-roll with beef (牛肉腸粉)", calories: 110, preference: 3 },
  { id: 23, name: "Steamed rice-roll with shrimp (鮮蝦腸粉)", calories: 81, preference: 3 },
  { id: 24, name: "Steamed rice-roll with scallops (帶子腸粉)", calories: 120, preference: 3 },
  { id: 25, name: "Steamed vegetarian rice-roll (羅漢齋腸粉)", calories: 60, preference: 3 },
  { id: 26, name: "Pan-fried rice-roll (煎腸粉)", calories: 150, preference: 3 },
  { id: 27, name: "Pan-fried turnip cake (煎蘿蔔糕)", calories: 180, preference: 3 },
  { id: 28, name: "Steamed turnip cake (蒸蘿蔔糕)", calories: 170, preference: 3 },
  { id: 29, name: "Taro cake (fried) (煎芋頭糕)", calories: 150, preference: 3 },
  { id: 30, name: "Pan-fried water chestnut cake (煎馬蹄糕)", calories: 110, preference: 3 },
  { id: 31, name: "Steamed water chestnut cake (馬蹄糕)", calories: 100, preference: 3 },
  { id: 32, name: "Taro cake (芋頭糕)", calories: 150, preference: 3 },
  { id: 33, name: "Curry fish ball rice (咖哩魚蛋飯)", calories: 700, preference: 3 },
  { id: 34, name: "Plain congee (白粥)", calories: 150, preference: 3 },
  { id: 35, name: "Chicken congee (雞肉粥)", calories: 180, preference: 3 },
  { id: 36, name: "Fish congee (魚片粥)", calories: 180, preference: 3 },
  { id: 37, name: "Beef congee (牛肉粥)", calories: 200, preference: 3 },
  { id: 38, name: "Pork & preserved egg congee (皮蛋瘦肉粥)", calories: 200, preference: 3 },
  { id: 39, name: "Century egg congee (皮蛋粥)", calories: 150, preference: 3 },
  { id: 40, name: "Pumpkin congee (南瓜粥)", calories: 150, preference: 3 },
  { id: 41, name: "Peanut congee (花生粥)", calories: 180, preference: 3 },
  { id: 42, name: "Eight-treasure sweet porridge (八寶粥)", calories: 200, preference: 3 },
  { id: 43, name: "Wonton noodles (soup) (雲吞湯麵)", calories: 631, preference: 3 },
  { id: 44, name: "Wonton noodles (dry) (乾撈雲吞麵)", calories: 600, preference: 3 },
  { id: 45, name: "Beef brisket noodles (牛腩麵)", calories: 700, preference: 3 },
  { id: 46, name: "Curry beef brisket noodles (咖哩牛腩麵)", calories: 700, preference: 3 },
  { id: 47, name: "Fish ball noodle soup (魚蛋湯麵)", calories: 400, preference: 3 },
  { id: 48, name: "Fish ball dry noodles (乾炒魚蛋麵)", calories: 450, preference: 3 },
  { id: 49, name: "Pan-fried plain noodles (乾炒撈麵)", calories: 450, preference: 3 },
  { id: 50, name: "Pan-fried curry noodles (乾炒咖哩麵)", calories: 600, preference: 3 },
  { id: 51, name: "Plain egg noodles (雞蛋麵)", calories: 300, preference: 3 },
  { id: 52, name: "Plain noodles (白麵)", calories: 300, preference: 3 },
  { id: 53, name: "Rice vermicelli (soup) (米粉湯)", calories: 350, preference: 3 },
  { id: 54, name: "Rice vermicelli (dry) (乾炒米粉)", calories: 400, preference: 3 },
  { id: 55, name: "Rice vermicelli with beef (牛肉米粉)", calories: 500, preference: 3 },
  { id: 56, name: "Shanghai-style noodles (上海粗炒麵)", calories: 400, preference: 3 },
  { id: 57, name: "Hong Kong-style chow mein (港式炒麵)", calories: 400, preference: 3 },
  { id: 58, name: "Scallion oil noodles (蔥油拌麵)", calories: 350, preference: 3 },
  { id: 59, name: "Tomato beef macaroni soup (鮮茄牛肉通粉)", calories: 350, preference: 3 },
  { id: 60, name: "Ham & egg macaroni soup (火腿蛋通心粉)", calories: 300, preference: 3 },
  { id: 61, name: "Baked macaroni with chicken (焗雞通粉)", calories: 450, preference: 3 },
  { id: 62, name: "Baked pork chop rice (焗豬扒飯)", calories: 700, preference: 3 },
  { id: 63, name: "Kimchi fried rice (泡菜炒飯)", calories: 600, preference: 3 },
  { id: 64, name: "Seafood fried rice (海鮮炒飯)", calories: 600, preference: 3 },
  { id: 65, name: "Kung Pao chicken (宮保雞丁)", calories: 400, preference: 3 },
  { id: 66, name: "Mapo tofu (麻婆豆腐)", calories: 400, preference: 3 },
  { id: 67, name: "Stir-fried morning glory (炒通菜)", calories: 150, preference: 3 },
  { id: 68, name: "Stir-fried Chinese broccoli (蠔油芥蘭)", calories: 150, preference: 3 },
  { id: 69, name: "Stir-fried lettuce (清炒生菜)", calories: 100, preference: 3 },
  { id: 70, name: "Stir-fried cabbage (炒椰菜)", calories: 150, preference: 3 },
  { id: 71, name: "Stir-fried garlic pork (蒜香肉片)", calories: 400, preference: 3 },
  { id: 72, name: "Sweet and sour pork (咕嚕肉)", calories: 400, preference: 3 },
  { id: 73, name: "Sweet and sour chicken (咕嚕雞球)", calories: 400, preference: 3 },
  { id: 74, name: "Salt and pepper pork ribs (椒鹽排骨)", calories: 350, preference: 3 },
  { id: 75, name: "Salt and pepper squid (椒鹽魷魚)", calories: 300, preference: 3 },
  { id: 76, name: "Salt and pepper shrimp (椒鹽蝦)", calories: 300, preference: 3 },
  { id: 77, name: "Steamed shrimp with garlic (蒜蓉蒸蝦)", calories: 300, preference: 3 },
  { id: 78, name: "Steamed fish with ginger (薑蔥蒸魚)", calories: 250, preference: 3 },
  { id: 79, name: "Deep-fried whole fish (oil-soaked) (油浸魚)", calories: 600, preference: 3 },
  { id: 80, name: "Steamed whole fish (清蒸魚)", calories: 200, preference: 3 },
  { id: 81, name: "Black bean clams (豉汁炒蜆)", calories: 300, preference: 3 },
  { id: 82, name: "Garlic clams (蒜蓉炒蜆)", calories: 300, preference: 3 },
  { id: 83, name: "Stir-fried beef with vegetables (牛肉炒菜心)", calories: 400, preference: 3 },
  { id: 84, name: "Spicy stir-fried chicken (乾煸雞丁)", calories: 400, preference: 3 },
  { id: 85, name: "Oyster omelette (蠔仔煎)", calories: 300, preference: 3 },
  { id: 86, name: "Scrambled egg with tomato (蕃茄炒蛋)", calories: 200, preference: 3 },
  { id: 87, name: "Stir-fried egg with chives (韭菜炒蛋)", calories: 180, preference: 3 },
  { id: 88, name: "Winter melon soup (冬瓜湯)", calories: 100, preference: 3 },
  { id: 89, name: "Pork bone soup (豬骨湯)", calories: 150, preference: 3 },
  { id: 90, name: "Fish maw soup (魚肚湯)", calories: 150, preference: 3 },
  { id: 91, name: "Flowering cabbage soup (菜心湯)", calories: 100, preference: 3 },
  { id: 92, name: "Ginseng chicken soup (人參雞湯)", calories: 200, preference: 3 },
  { id: 93, name: "Seaweed egg soup (紫菜蛋花湯)", calories: 100, preference: 3 },
  { id: 94, name: "Hot and sour soup (酸辣湯)", calories: 80, preference: 3 },
  { id: 95, name: "Mixed vegetable soup (什菜湯)", calories: 80, preference: 3 },
  { id: 96, name: "Corn egg drop soup (粟米蛋花湯)", calories: 100, preference: 3 },
  { id: 97, name: "Bitter gourd pork soup (苦瓜排骨湯)", calories: 120, preference: 3 },
  { id: 98, name: "Roast pork (Char siu) (叉燒)", calories: 350, preference: 3 },
  { id: 99, name: "Roast duck (燒鴨)", calories: 300, preference: 3 },
  { id: 100, name: "Soy sauce chicken (豉油雞)", calories: 300, preference: 3 },
  { id: 101, name: "White cut chicken (白切雞)", calories: 300, preference: 3 },
  { id: 102, name: "Curry chicken wings (咖哩雞翼)", calories: 250, preference: 3 },
  { id: 103, name: "Soy sauce pork trotters (豉油豬手)", calories: 400, preference: 3 },
  { id: 104, name: "Braised pork belly (紅燒肉)", calories: 500, preference: 3 },
  { id: 105, name: "Steamed chicken in black bean sauce (豉汁蒸雞)", calories: 300, preference: 3 },
  { id: 106, name: "Sweet & sour pork ribs (糖醋排骨)", calories: 350, preference: 3 },
  { id: 107, name: "Curry goat with potatoes (咖哩羊腩)", calories: 500, preference: 3 },
  { id: 108, name: "BBQ pork (叉燒)", calories: 350, preference: 3 },
  { id: 109, name: "BBQ pork bun (steamed) (叉燒包)", calories: 180, preference: 3 },
  { id: 110, name: "Barbecue pork puff (Baked) (叉燒酥)", calories: 200, preference: 3 },
  { id: 111, name: "Steamed pork ribs with black bean sauce (豉汁蒸排骨)", calories: 260, preference: 3 },
  { id: 112, name: "Steamed chicken bun (雞包仔)", calories: 120, preference: 3 },
  { id: 113, name: "Salted fish fried rice (鹹魚雞粒炒飯)", calories: 500, preference: 3 },
  { id: 114, name: "Garlic clam vermicelli (蒜茸炒米粉 (蜆))", calories: 400, preference: 3 },
  { id: 115, name: "Steamed scallops with vermicelli (粉絲蒸帶子)", calories: 300, preference: 3 },
  { id: 116, name: "Fried prawn balls (炸蝦球)", calories: 400, preference: 3 },
  { id: 117, name: "Shrimp toast (蝦多士)", calories: 300, preference: 3 },
  { id: 118, name: "Honey walnut shrimp (合桃蝦球)", calories: 400, preference: 3 },
  { id: 119, name: "Oyster omelette (蠔仔煎)", calories: 300, preference: 3 },
  { id: 120, name: "Steamed mussels with vermicelli (粉絲蒸海虹)", calories: 300, preference: 3 },
  { id: 121, name: "Salt and pepper tofu (椒鹽豆腐)", calories: 250, preference: 3 },
  { id: 122, name: "Stir-fried tofu with vegetables (炒雜菜豆腐)", calories: 250, preference: 3 },
  { id: 123, name: "Braised tofu with mushrooms (紅燒豆腐)", calories: 250, preference: 3 },
  { id: 124, name: "Eggplant in garlic sauce (魚香茄子)", calories: 300, preference: 3 },
  { id: 125, name: "Broccoli in oyster sauce (蠔油芥蘭)", calories: 200, preference: 3 },
  { id: 126, name: "Spinach in oyster sauce (蠔油菠菜)", calories: 150, preference: 3 },
  { id: 127, name: "Stir-fried lotus root (清炒蓮藕)", calories: 150, preference: 3 },
  { id: 128, name: "Braised eggplant with pork (肉燒茄子)", calories: 300, preference: 3 },
  { id: 129, name: "Stir-fried bitter melon (炒苦瓜)", calories: 150, preference: 3 },
  { id: 130, name: "Steamed egg custard bun (奶皇包)", calories: 180, preference: 3 },
  { id: 131, name: "Steamed lotus seed paste bun (蓮蓉包)", calories: 160, preference: 3 },
  { id: 132, name: "Steamed vegetable bun (素菜包)", calories: 150, preference: 3 },
  { id: 133, name: "Steamed red bean bun (豆沙包)", calories: 150, preference: 3 },
  { id: 134, name: "Shrimp dumplings (Har Gow) (蝦餃)", calories: 150, preference: 3 },
  { id: 135, name: "Pork siu mai (steamed) (燒賣)", calories: 100, preference: 3 },
  { id: 136, name: "Shanghai soup dumpling (Xiao Long Bao) (小籠包)", calories: 100, preference: 3 },
  { id: 137, name: "Vegetarian steamed dumpling (上素蒸粉果)", calories: 80, preference: 3 },
  { id: 138, name: "Beef balls (牛肉丸)", calories: 150, preference: 3 },
  { id: 139, name: "Chicken feet in black bean sauce (豉汁蒸鳳爪)", calories: 200, preference: 3 },
  { id: 140, name: "Chicken feet (braised style) (紅燒鳳爪)", calories: 200, preference: 3 },
  { id: 141, name: "Fish maw soup (魚肚湯)", calories: 150, preference: 3 },
  { id: 142, name: "Pineapple bun (菠蘿包)", calories: 290, preference: 3 },
  { id: 143, name: "Butter pineapple bun (with butter) (菠蘿油)", calories: 300, preference: 3 },
  { id: 144, name: "Cocktail bun (雞尾包)", calories: 250, preference: 3 },
  { id: 145, name: "Egg tart (蛋撻)", calories: 86, preference: 3 },
  { id: 146, name: "Coconut tart (椰撻)", calories: 180, preference: 3 },
  { id: 147, name: "Wife cake (老婆餅)", calories: 150, preference: 3 },
  { id: 148, name: "Butterfly cookie (蝴蝶酥)", calories: 150, preference: 3 },
  { id: 149, name: "Almond biscuit (杏仁餅)", calories: 100, preference: 3 },
  { id: 150, name: "Satay beef puff (沙嗲牛肉酥)", calories: 200, preference: 3 },
  { id: 151, name: "Baked barbecue pork bun (焗叉燒包)", calories: 200, preference: 3 },
  { id: 152, name: "Chinese New Year lotus seed cake (Nian Gao) (年糕)", calories: 200, preference: 3 },
  { id: 153, name: "Egg waffle (雞蛋仔)", calories: 330, preference: 3 },
  { id: 154, name: "Hong Kong-style egg pancake (班戟)", calories: 200, preference: 3 },
  { id: 155, name: "Custard bun (奶黃包)", calories: 200, preference: 3 },
  { id: 156, name: "Mango pancake (芒果班戟)", calories: 200, preference: 3 },
  { id: 157, name: "Snow-skin mooncake (冰皮月餅)", calories: 150, preference: 3 },
  { id: 158, name: "Lotus-seed mooncake (蓮蓉月餅)", calories: 200, preference: 3 },
  { id: 159, name: "Red bean mooncake (豆沙月餅)", calories: 200, preference: 3 },
  { id: 160, name: "Sweet rice dumplings (湯圓)", calories: 200, preference: 3 },
  { id: 161, name: "Almond tofu (杏仁豆腐)", calories: 100, preference: 3 },
  { id: 162, name: "Grass jelly (涼粉)", calories: 50, preference: 3 },
  { id: 163, name: "Black sesame soup (芝麻糊)", calories: 250, preference: 3 },
  { id: 164, name: "Red bean soup (紅豆沙)", calories: 150, preference: 3 },
  { id: 165, name: "Green bean soup (綠豆沙)", calories: 150, preference: 3 },
  { id: 166, name: "Ginkgo nut in syrup (白果糖水)", calories: 100, preference: 3 },
  { id: 167, name: "Sweet potato dessert (蕃薯糖水)", calories: 150, preference: 3 },
  { id: 168, name: "Butter cake (牛油蛋糕)", calories: 300, preference: 3 },
  { id: 169, name: "Mango pudding (芒果布甸)", calories: 300, preference: 3 },
  { id: 170, name: "Egg pudding (雞蛋布甸)", calories: 250, preference: 3 },
  { id: 171, name: "Swiss roll with red bean (紅豆蛋糕卷)", calories: 400, preference: 3 },
  { id: 172, name: "Flaky egg roll (蛋卷)", calories: 150, preference: 3 },
  { id: 173, name: "Mosaic cake (鏡餅)", calories: 150, preference: 3 },
  { id: 174, name: "Corn soup (with ham) (火腿粟米羹)", calories: 150, preference: 3 },
  { id: 175, name: "Tomato egg drop soup (蕃茄蛋花湯)", calories: 100, preference: 3 },
  { id: 176, name: "Korean seaweed soup (韓式紫菜湯)", calories: 100, preference: 3 },
  { id: 177, name: "Peanut soup (with glutinous balls) (紅豆沙湯圓)", calories: 250, preference: 3 },
  { id: 178, name: "Sesame ball dessert (芝麻糊湯圓)", calories: 250, preference: 3 },
  { id: 179, name: "Steamed beef & egg cake (蒸牛肉蛋糕)", calories: 200, preference: 3 },
  { id: 180, name: "Steamed pork & egg cake (蒸豬肉蛋糕)", calories: 200, preference: 3 },
  { id: 181, name: "Ham cake (Ham seng) (冬瓜糕)", calories: 150, preference: 3 },
  { id: 182, name: "Rice ball with peanut & pork floss (肉鬆蛋黃糯米糍)", calories: 300, preference: 3 },
  { id: 183, name: "Fried dough sticks with soy milk (油條配豆漿)", calories: 400, preference: 3 },
  { id: 184, name: "Butter toast with jam (牛油多士)", calories: 200, preference: 3 },
  { id: 185, name: "French toast with egg (雞蛋西多士)", calories: 300, preference: 3 },
  { id: 186, name: "Hong Kong-style instant noodles (公仔麵)", calories: 400, preference: 3 },
  { id: 187, name: "Steamed rice rolls with sesame sauce (芝麻醬腸粉)", calories: 120, preference: 3 },
  { id: 188, name: "Shrimp paste with fish maw (蝦膏魚鰾)", calories: 150, preference: 3 },
  { id: 189, name: "Chinese sausage omelette (臘腸煎蛋)", calories: 300, preference: 3 },
  { id: 190, name: "Lotus root pork soup (蓮藕排骨湯)", calories: 120, preference: 3 },
  { id: 191, name: "Cordyceps chicken soup (蟲草花豬骨湯)", calories: 150, preference: 3 },
  { id: 192, name: "Cordyceps flower chicken soup (蟲草花雞湯)", calories: 150, preference: 3 },
  { id: 193, name: "Pumpkin dessert soup (南瓜湯)", calories: 100, preference: 3 },
  { id: 194, name: "Almond soup (杏仁糊)", calories: 200, preference: 3 },
  { id: 195, name: "Lotus seed soup (蓮子糖水)", calories: 100, preference: 3 },
  { id: 196, name: "Black fungus pork slices (木耳炒肉片)", calories: 200, preference: 3 },
  { id: 197, name: "Braised tofu with seafood (海鮮豆腐煲)", calories: 400, preference: 3 },
  { id: 198, name: "Mixed vegetable congee (什菜粥)", calories: 150, preference: 3 },
  { id: 199, name: "Garlic & chive egg wrap (韭菜煎蛋餅)", calories: 250, preference: 3 },
  { id: 200, name: "Oyster sauce chow mein (蠔油撈麵)", calories: 450, preference: 3 },
  { id: 201, name: "Fried fish skin (炸魚皮)", calories: 200, preference: 3 },
  { id: 202, name: "Stir-fried lotus root & pork (蓮藕炒肉)", calories: 200, preference: 3 },
  { id: 203, name: "Spicy pickled soup (酸菜粉絲湯)", calories: 200, preference: 3 },
  { id: 204, name: "Green bean soup (chilled) (冰綠豆湯)", calories: 50, preference: 3 },
  { id: 205, name: "Stir-fried snow pea shoots (炒豆苗)", calories: 150, preference: 3 },
  { id: 206, name: "Boiled lettuce (no sauce) (白灼生菜)", calories: 50, preference: 3 },
  { id: 207, name: "Boiled Chinese broccoli (no sauce) (白灼菜心)", calories: 50, preference: 3 },
  { id: 208, name: "Boiled water spinach (no sauce) (白灼通菜)", calories: 50, preference: 3 },
  { id: 209, name: "Stir-fried spinach (炒菠菜)", calories: 150, preference: 3 },
  { id: 210, name: "Stir-fried bitter gourd (炒苦瓜)", calories: 150, preference: 3 },
  { id: 211, name: "Beef with green peppers (青椒牛肉)", calories: 400, preference: 3 },
  { id: 212, name: "Cashew chicken (腰果雞丁)", calories: 400, preference: 3 },
  { id: 213, name: "Thai-style hot & sour soup (泰式酸辣湯)", calories: 80, preference: 3 },
  { id: 214, name: "Chinese yam soup (山藥排骨湯)", calories: 120, preference: 3 },
  { id: 215, name: "Melon & pork rib soup (黃瓜排骨湯)", calories: 120, preference: 3 },
  { id: 216, name: "Chinese fried donut (糖環)", calories: 150, preference: 3 },
  { id: 217, name: "Beef tendon & brisket (牛腩牛筋)", calories: 350, preference: 3 },
  { id: 218, name: "Stewed braised pork (紅燒排骨)", calories: 350, preference: 3 },
  { id: 219, name: "Sea cucumber (海參)", calories: 500, preference: 3 },
  { id: 220, name: "Braised pork feet (紅燒豬腳)", calories: 400, preference: 3 },
  { id: 221, name: "Chicken gizzard (雞胗)", calories: 100, preference: 3 },
  { id: 222, name: "Duck web (鴨掌)", calories: 100, preference: 3 },
  { id: 223, name: "Imitation shark’s fin soup (魚翅羹)", calories: 200, preference: 3 },
  { id: 224, name: "Bird’s nest soup (燕窩)", calories: 200, preference: 3 },
  { id: 225, name: "Pineapple cake (鳳梨酥)", calories: 150, preference: 3 },
  { id: 226, name: "Taiyaki/Sun cake (太陽餅)", calories: 100, preference: 3 },
  { id: 227, name: "Ham & cheese sandwich (火腿芝士三文治)", calories: 300, preference: 3 },
  { id: 228, name: "Club sandwich (總匯三文治)", calories: 400, preference: 3 },
  { id: 229, name: "Curry puff (咖哩角)", calories: 200, preference: 3 },
  { id: 230, name: "Chicken pie (雞批)", calories: 250, preference: 3 },
  { id: 231, name: "Corn pie (粟米批)", calories: 250, preference: 3 },
  { id: 232, name: "Hamburger (fast food) (漢堡包)", calories: 500, preference: 3 },
  { id: 233, name: "Silken tofu pudding (豆花)", calories: 170, preference: 3 },
  { id: 234, name: "Tofu skin roll (Skui Jor) (石榴包)", calories: 200, preference: 3 },
  { id: 235, name: "Chicken glutinous rice (shark’s fin congee) (砂鍋雞飯)", calories: 400, preference: 3 },
  { id: 236, name: "Braised minced pork rice (Lu Rou Fan) (魯肉飯)", calories: 500, preference: 3 },
  { id: 237, name: "Egg sandwich (Hong Kong style) (蛋治)", calories: 300, preference: 3 },
  { id: 238, name: "Mixed fruit salad (雜果沙律)", calories: 350, preference: 3 },
  { id: 239, name: "Hainanese chicken rice (海南雞飯)", calories: 600, preference: 3 },
  { id: 240, name: "Chicken curry with coconut (椰汁咖哩雞)", calories: 500, preference: 3 },
  { id: 241, name: "Satay beef instant noodles (沙嗲牛肉公仔麵)", calories: 700, preference: 3 },
  { id: 242, name: "Ramen noodles (拉麵)", calories: 500, preference: 3 },
  { id: 243, name: "Udon noodles (烏冬麵)", calories: 450, preference: 3 },
  { id: 244, name: "Boiled dumplings (shui jiao) (水餃)", calories: 100, preference: 3 },
  { id: 245, name: "Pan-fried dumplings (potstickers) (煎餃)", calories: 150, preference: 3 },
  { id: 246, name: "Steamed clam soup (蜆湯)", calories: 100, preference: 3 },
  { id: 247, name: "Deep-fried doughnut (yau za gwai) (油條)", calories: 150, preference: 3 },
  { id: 248, name: "Chive pockets (韭菜盒子)", calories: 200, preference: 3 },
  { id: 249, name: "Minced meat pancake (薄餅)", calories: 100, preference: 3 },
  { id: 250, name: "Milkfish congee (虱目魚粥)", calories: 180, preference: 3 },
  { id: 251, name: "Catfish congee (鱸魚粥)", calories: 180, preference: 3 },
  { id: 252, name: "Clam congee (蜆仔粥)", calories: 180, preference: 3 },
  { id: 253, name: "Pork liver congee (豬肝粥)", calories: 180, preference: 3 },
  { id: 254, name: "Cuttlefish congee (墨魚粥)", calories: 180, preference: 3 },
  { id: 255, name: "Steamed beef ball (蒸牛肉丸)", calories: 100, preference: 3 },
  { id: 256, name: "Steamed fish ball (蒸魚蛋)", calories: 100, preference: 3 },
  { id: 257, name: "Steamed chicken ball (蒸雞肉丸)", calories: 100, preference: 3 },
  { id: 258, name: "Steamed pig trotter (蒸豬手)", calories: 200, preference: 3 },
  { id: 259, name: "Chinese crepe (jianbing) (煎餅)", calories: 300, preference: 3 },
  { id: 260, name: "Mouthwatering chicken (口水雞)", calories: 300, preference: 3 },
  { id: 261, name: "Chinese cold platter (lou shui) (滷水拼盤)", calories: 300, preference: 3 },
  { id: 262, name: "Century egg tofu (皮蛋豆腐)", calories: 150, preference: 3 },
  { id: 263, name: "Crispy taro dumpling (yu gok) (芋角)", calories: 150, preference: 3 },
  { id: 264, name: "Stir-fried bean curd skin rolls (炒腐皮卷)", calories: 250, preference: 3 },
  { id: 265, name: "Steamed beef in ginger-scallion sauce (薑葱牛肉)", calories: 400, preference: 3 },
  { id: 266, name: "Braised pork with preserved vegetables (梅菜扣肉)", calories: 350, preference: 3 },
  { id: 267, name: "Steamed chicken with mushrooms (冬菇蒸雞)", calories: 300, preference: 3 },
  { id: 268, name: "Steamed fish tofu (蒸魚豆腐)", calories: 150, preference: 3 },
  { id: 269, name: "Stir-fried bitter melon with egg (苦瓜炒蛋)", calories: 150, preference: 3 },
  { id: 270, name: "Sichuan boiled fish (水煮魚)", calories: 500, preference: 3 },
  { id: 271, name: "Hakka stir-fry (kek lok) (客家小炒)", calories: 400, preference: 3 },
  { id: 272, name: "Chinese steamed egg (茶碗蒸)", calories: 100, preference: 3 },
  { id: 273, name: "Fried century egg (煎皮蛋)", calories: 150, preference: 3 },
  { id: 274, name: "Salt-baked chicken (鹽焗雞)", calories: 400, preference: 3 },
  { id: 275, name: "Grilled pork chop (烤豬扒)", calories: 400, preference: 3 },
  { id: 276, name: "Fried chicken fillet (炸雞柳)", calories: 300, preference: 3 },
  { id: 277, name: "Garlic chili fish (蒜香辣魚)", calories: 500, preference: 3 },
  { id: 278, name: "Oyster sauce clams (蠔油炒蜆)", calories: 300, preference: 3 },
  { id: 279, name: "Lemon butter fish (檸檬魚片)", calories: 250, preference: 3 },
  { id: 280, name: "Beef brain curry (咖喱牛腦)", calories: 500, preference: 3 },
  { id: 281, name: "Leek & egg pancake (jiaozi) (韭菜盒子)", calories: 200, preference: 3 },
  { id: 282, name: "Chinese donut (糖環)", calories: 150, preference: 3 },
  { id: 283, name: "Salted chicken (yan juk gai) (鹽焗雞)", calories: 400, preference: 3 },
  { id: 284, name: "Fish paste rolls (墨魚丸)", calories: 150, preference: 3 },
  { id: 285, name: "Tofu pudding (douhua) (豆腐花)", calories: 170, preference: 3 },
  { id: 286, name: "Mixed bean sweet soup (ja-ja bowl) (喳咋)", calories: 150, preference: 3 },
  { id: 287, name: "Corn custard (粟米仔)", calories: 150, preference: 3 },
  { id: 288, name: "Papaya snow fungus soup (雪耳木瓜糖水)", calories: 100, preference: 3 },
  { id: 289, name: "Almond jelly (杏仁豆腐)", calories: 100, preference: 3 },
  { id: 290, name: "Thousand-layer cake (wanshou gao) (萬壽糕)", calories: 150, preference: 3 },
  { id: 291, name: "Glutinous rice balls in ginger soup (湯圓薑湯)", calories: 200, preference: 3 },
  { id: 292, name: "Red bean ice pops (冰紅豆)", calories: 50, preference: 3 },
  { id: 293, name: "Fruit platter (水果拼盤)", calories: 200, preference: 3 },
  { id: 294, name: "Sun cake (Taiyang bing) (太陽餅)", calories: 100, preference: 3 },
  { id: 295, name: "Beef tendon & pork noodle soup (牛筋湯麵)", calories: 500, preference: 3 },
  { id: 296, name: "Lobster noodles (龍蝦湯麵)", calories: 800, preference: 3 },
  { id: 297, name: "Seafood hot pot (海鮮煲)", calories: 600, preference: 3 },
  { id: 298, name: "Barbecue platter (3 meats) (燒味拼盤)", calories: 500, preference: 3 },
  { id: 299, name: "Pineapple custard bun (菠蘿奶黃包)", calories: 300, preference: 3 },
  { id: 300, name: "Egg & scallion pancake (蛋餅)", calories: 250, preference: 3 },
  { id: 301, name: "Crispy garlic chicken ribs (蒜香雞脆骨)", calories: 300, preference: 3 },
  { id: 302, name: "Watercress soup (西洋菜湯)", calories: 100, preference: 3 },
  { id: 303, name: "Century egg & ginger soup (皮蛋薑湯)", calories: 100, preference: 3 },
  { id: 304, name: "Vegetarian spring roll (素春卷)", calories: 200, preference: 3 },
  { id: 305, name: "Vegetarian siu mai (素燒賣)", calories: 80, preference: 3 },
  { id: 306, name: "Vegetarian mushroom bun (香菇素包)", calories: 150, preference: 3 },
  { id: 307, name: "Vegetarian curry bun (咖哩素包)", calories: 200, preference: 3 },
  { id: 308, name: "Vegetarian shrimp dumpling (素蝦餃)", calories: 100, preference: 3 },
  { id: 309, name: "Vegetarian cold platter (素拼盤)", calories: 150, preference: 3 },
  { id: 310, name: "Seaweed and tofu soup (紫菜豆腐湯)", calories: 80, preference: 3 },
  { id: 311, name: "Curry instant noodles with spam & egg (咖哩公仔麵)", calories: 750, preference: 3 },
  { id: 312, name: "Dry-fried Yu myun (薄切粥) (粥仔)", calories: 150, preference: 3 },
  { id: 313, name: "Mixed instant noodles (雜錦公仔麵)", calories: 600, preference: 3 },
  { id: 314, name: "Instant noodle with luncheon meat (公仔麵加午餐肉)", calories: 500, preference: 3 },
  { id: 315, name: "Instant noodle with chicken luncheon meat (公仔麵加鹹雞肉)", calories: 500, preference: 3 },
  { id: 316, name: "Rice noodle rolls with soy sauce (豉油王腸粉)", calories: 100, preference: 3 },
  { id: 317, name: "Egg and chive dumplings (韭菜豬肉餃)", calories: 100, preference: 3 },
  { id: 318, name: "Chinese hamburger (rou jia mo) (肉夾饃)", calories: 400, preference: 3 },
  { id: 319, name: "Egg sandwich (蛋三文治)", calories: 250, preference: 3 },
  { id: 320, name: "Vegetable salad (雜菜沙律)", calories: 200, preference: 3 },
  { id: 321, name: "Curry pork chop on rice (咖哩豬扒飯)", calories: 500, preference: 3 },
  { id: 322, name: "Gyudon (Japanese beef bowl) (牛丼)", calories: 600, preference: 3 },
  { id: 323, name: "Hong Kong fishball noodles (魚蛋湯麵)", calories: 400, preference: 3 },
  { id: 324, name: "Fried wontons (炸雲吞)", calories: 150, preference: 3 },
  { id: 325, name: "Water chestnut cake (馬蹄糕)", calories: 100, preference: 3 },
  { id: 326, name: "Mango sago with pomelo (楊枝甘露)", calories: 210, preference: 3 },
  { id: 327, name: "Coconut milk yellow bean pudding (椰汁馬豆糕)", calories: 120, preference: 3 },
  { id: 328, name: "Sesame paste sweet soup (芝麻糊)", calories: 250, preference: 3 },
  { id: 329, name: "Mixed bean sweet soup (Gingko dessert) (喳咋)", calories: 150, preference: 3 },
  { id: 330, name: "Pumpkin pudding (南瓜布丁)", calories: 150, preference: 3 },
  { id: 331, name: "Peanut soup (花生湯)", calories: 150, preference: 3 },
  { id: 332, name: "Rice congee with century egg (皮蛋瘦肉粥)", calories: 200, preference: 3 },
  { id: 333, name: "Rice congee with minced pork (薑葱豬肉粥)", calories: 200, preference: 3 },
  { id: 334, name: "Rice congee with dried scallop (瑤柱粥)", calories: 200, preference: 3 },
  { id: 335, name: "Orange beef hot pot (柑橘牛肉煲)", calories: 500, preference: 3 },
  { id: 336, name: "Vegetable hot pot (蔬菜煲)", calories: 400, preference: 3 },
  { id: 337, name: "Beef with green pepper (青椒牛肉)", calories: 400, preference: 3 },
  { id: 338, name: "Vegetarian hot pot (素菜煲)", calories: 300, preference: 3 },
  { id: 339, name: "Century egg and pork porridge (皮蛋瘦肉粥)", calories: 200, preference: 3 },
  { id: 340, name: "Salted pork porridge (臘腸粥)", calories: 200, preference: 3 },
  { id: 341, name: "Congee with fish balls (魚蛋粥)", calories: 180, preference: 3 },
  { id: 342, name: "Garlic fried rice (蒜香炒飯)", calories: 600, preference: 3 },
  { id: 343, name: "Vegetarian claypot (素煲仔飯)", calories: 500, preference: 3 },
  { id: 344, name: "Minced pork and salted egg congee (鹹蛋肉碎粥)", calories: 200, preference: 3 },
  { id: 345, name: "Vietnamese pho (beef) (越南牛肉粉)", calories: 600, preference: 3 },
  { id: 346, name: "Western-style barbecue sauce spaghetti (西式肉醬意粉)", calories: 500, preference: 3 },
  { id: 347, name: "Curry soup with fish balls (咖喱魚蛋湯)", calories: 250, preference: 3 },
  { id: 348, name: "Stir-fried rice noodles with beef (乾炒牛河)", calories: 970, preference: 3 },
  { id: 349, name: "Stir-fried noodles with seafood (海鮮炒烏冬)", calories: 890, preference: 3 },
  { id: 350, name: "Stir-fried noodles with soy sauce (豉油皇炒麵)", calories: 450, preference: 3 },
  { id: 351, name: "Cha Siu rice (half fat/lean) (半肥瘦叉燒飯)", calories: 720, preference: 3 },
  { id: 352, name: "Cha Siu rice (lean only) (瘦叉燒飯)", calories: 650, preference: 3 },
  { id: 353, name: "Claypot frog legs (田雞煲仔飯)", calories: 500, preference: 3 },
  { id: 354, name: "Claypot dried salted fish rice (鹹魚雞粒飯)", calories: 500, preference: 3 },
  { id: 355, name: "Stir-fried beef with ginger & scallion (薑蔥牛肉)", calories: 400, preference: 3 },
  { id: 356, name: "Stir-fried shredded squid with ginger (姜蔥炒魷魚)", calories: 350, preference: 3 },
  { id: 357, name: "Egg lo hei (prosperity dish) (撈起)", calories: 300, preference: 3 },
  { id: 358, name: "Stir-fried beef with onion (洋蔥炒牛肉)", calories: 400, preference: 3 },
  { id: 359, name: "Beef brisket stew (Korean style) (韓式牛腩煲)", calories: 500, preference: 3 },
  { id: 360, name: "Teriyaki chicken rice (照燒雞扒飯)", calories: 600, preference: 3 },
  { id: 361, name: "Tonkatsu curry rice (豬扒咖哩飯)", calories: 600, preference: 3 },
  { id: 362, name: "Hong Kong-style fried chicken (香港炸雞)", calories: 500, preference: 3 },
  { id: 363, name: "Spicy beef salad (麻辣牛肉片)", calories: 300, preference: 3 },
  { id: 364, name: "Vietnamese grilled pork rice (越南烤肉飯)", calories: 500, preference: 3 },
  { id: 365, name: "Steamed chicken feet (garlic style) (蒜蓉鳳爪)", calories: 200, preference: 3 },
  { id: 366, name: "Spicy grilled beef (黑椒牛仔骨)", calories: 400, preference: 3 },
  { id: 367, name: "Fried tofu with basil leaves (九層塔炒豆腐)", calories: 250, preference: 3 },
  { id: 368, name: "Spicy fish soup (Thailand) (泰式咖哩魚湯)", calories: 250, preference: 3 },
  { id: 369, name: "Rice noodle rolls (dry) (乾腸粉)", calories: 80, preference: 3 },
  { id: 370, name: "Steamed red bean paste bun (豆沙包)", calories: 150, preference: 3 },
  { id: 371, name: "Steamed pork & shrimp siu mai (燒賣)", calories: 100, preference: 3 },
  { id: 372, name: "BBQ pork sticky rice (Lo Mai Gai) (糯米雞)", calories: 400, preference: 3 },
  { id: 373, name: "Thai chicken rice (泰式雞飯)", calories: 600, preference: 3 },
  { id: 374, name: "Vietnamese grilled pork noodles (越南烤肉粉)", calories: 500, preference: 3 },
  { id: 375, name: "Stir-fried bitter melon & pork (苦瓜炒肉片)", calories: 250, preference: 3 },
  { id: 376, name: "Congee with tripe (豬肚粥)", calories: 200, preference: 3 },
  { id: 377, name: "Fish maw & mushroom congee (魚肚瑤柱粥)", calories: 200, preference: 3 },
  { id: 378, name: "Clam vermicelli soup (蛤蜊湯米粉)", calories: 150, preference: 3 },
  { id: 379, name: "Winter melon & spare rib soup (冬瓜排骨湯)", calories: 120, preference: 3 },
  { id: 380, name: "Ginger & vinegar pig’s feet (豬手醋)", calories: 400, preference: 3 },
  { id: 381, name: "Chicken with fermented bean curd (腐乳雞)", calories: 300, preference: 3 },
  { id: 382, name: "Braised duck rice (Hong Kong style) (鴨飯)", calories: 450, preference: 3 },
  { id: 383, name: "Crispy pork belly (脆皮燒肉)", calories: 450, preference: 3 },
  { id: 384, name: "Fish paste dumplings (3) (魚蓉餃)", calories: 100, preference: 3 },
  { id: 385, name: "Wonton dumplings (3) (雲吞)", calories: 150, preference: 3 },
  { id: 386, name: "Rice cracker snack (米通)", calories: 100, preference: 3 },
  { id: 387, name: "Pineapple bun with ham & butter (火腿菠蘿包)", calories: 350, preference: 3 },
  { id: 388, name: "Hong Kong milk tea (no sugar) (凍奶茶 (無糖))", calories: 0, preference: 3 },
  { id: 389, name: "Hong Kong lemon tea (no sugar) (凍檸茶 (無糖))", calories: 0, preference: 3 },
  { id: 390, name: "Seasonal mixed fruit (時令水果)", calories: 100, preference: 3 },
  { id: 391, name: "Fruit ice jelly (水果冰)", calories: 150, preference: 3 },
  { id: 392, name: "Green tea mochi (抹茶麻糬)", calories: 150, preference: 3 },
  { id: 393, name: "Brown sugar mochi (紅糖糍粑)", calories: 150, preference: 3 },
  { id: 394, name: "Steamed fish head with chili sauce (剁椒蒸魚頭)", calories: 400, preference: 3 },
  { id: 395, name: "Baked French fries (焗薯條)", calories: 250, preference: 3 },
  { id: 396, name: "Hamburger steak with gravy (漢堡扒)", calories: 400, preference: 3 },
  { id: 397, name: "Vegetable & tofu hot pot (素食煲)", calories: 400, preference: 3 },
  { id: 398, name: "Japanese curry udon (日式咖哩烏冬)", calories: 600, preference: 3 },
  { id: 399, name: "Rice porridge with preserved vegetables (酸菜白肉粥)", calories: 150, preference: 3 },
  { id: 400, name: "Stir-fried pork intestine with peppers (青椒炒大腸)", calories: 250, preference: 3 },
  { id: 401, name: "Congee with peanuts & pork (花生瘦肉粥)", calories: 180, preference: 3 },
  { id: 402, name: "Beef tendon & tripe congee (牛筋牛肚粥)", calories: 200, preference: 3 },
  { id: 403, name: "Stir-fried mixed vegetables (炒雜菜)", calories: 200, preference: 3 },
  { id: 404, name: "Sweetcorn porridge (粟米粥)", calories: 150, preference: 3 },
  { id: 405, name: "Stir-fried shredded pork with green pepper (青椒肉絲)", calories: 400, preference: 3 },
  { id: 406, name: "Stir-fried beef with black bean sauce (豉汁炒牛肉)", calories: 400, preference: 3 },
  { id: 407, name: "Steamed chicken with lemon (檸檬雞)", calories: 400, preference: 3 },
  { id: 408, name: "Stir-fried duck tongue (炒鴨舌)", calories: 150, preference: 3 },
  { id: 409, name: "Barbecue pork spare ribs (蜜汁叉燒骨)", calories: 400, preference: 3 },
  { id: 410, name: "Chicken wings (roasted) (烤雞翼)", calories: 180, preference: 3 },
  { id: 411, name: "Steamed soy sauce chicken bun (雞包仔)", calories: 120, preference: 3 },
  { id: 412, name: "Salted egg yolk pastry (蛋黃酥)", calories: 200, preference: 3 },
  { id: 413, name: "Mango mochi (芒果糯米糍)", calories: 150, preference: 3 },
  { id: 414, name: "Pumpkin pancakes (南瓜煎餅)", calories: 150, preference: 3 },
  { id: 415, name: "Wheat gluten vegetarian rolls (燒賣)", calories: 80, preference: 3 },
  { id: 416, name: "Seafood & meat claypot (海鮮煲仔飯)", calories: 600, preference: 3 },
  { id: 417, name: "Curry chicken fillet on rice (咖哩雞扒飯)", calories: 600, preference: 3 },
  { id: 418, name: "Spicy green pepper & beef (青椒牛肉炒)", calories: 400, preference: 3 },
  { id: 419, name: "Hot & sour pork soup (酸辣排骨湯)", calories: 120, preference: 3 },
  { id: 420, name: "Lemon beef pie (檸檬牛肉餅)", calories: 300, preference: 3 },
  { id: 421, name: "Fried chicken leg (炸雞腿)", calories: 500, preference: 3 },
  { id: 422, name: "Steamed beef patty (蒸肉餅)", calories: 150, preference: 3 },
  { id: 423, name: "Stir-fried eggplant in black bean sauce (豆鼓蒜茸茄子)", calories: 250, preference: 3 },
  { id: 424, name: "Deep-fried fish fillet (炸魚柳)", calories: 300, preference: 3 },
  { id: 425, name: "Stir-fried celery with shrimp (西芹炒蝦仁)", calories: 250, preference: 3 },
  { id: 426, name: "Stir-fried pork belly with leeks (蔥爆五花肉)", calories: 400, preference: 3 },
  { id: 427, name: "Fried doughnut (glutinous) (麻花)", calories: 150, preference: 3 },
  { id: 428, name: "Fish maw with pepper (椒鹽魚肚)", calories: 250, preference: 3 },
  { id: 429, name: "Garlic pepper shrimp toast (蒜香蝦多士)", calories: 300, preference: 3 },
  { id: 430, name: "Egg omelette with mushrooms (蘑菇煎蛋)", calories: 200, preference: 3 },
  { id: 431, name: "Fresh milk cake (Hong Kong style) (燉奶)", calories: 150, preference: 3 },
  { id: 432, name: "Tapioca pearls (珍珠)", calories: 100, preference: 3 },
  { id: 433, name: "Stir-fried octopus (蠔油炒章魚)", calories: 300, preference: 3 },
  { id: 434, name: "Pan-fried fish dumplings (煎魚餃)", calories: 150, preference: 3 },
  { id: 435, name: "Steamed beef patty with salted egg (蒸魚蓉蛋餅)", calories: 150, preference: 3 },
  { id: 436, name: "Hotpot with beef & tripe (牛腩火鍋)", calories: 600, preference: 3 },
  { id: 437, name: "Hong Kong-style curry udon (咖哩烏冬)", calories: 500, preference: 3 },
  { id: 438, name: "Japanese-style curry rice (日式咖哩飯)", calories: 600, preference: 3 },
  { id: 439, name: "Okonomiyaki (savory pancake)", calories: 400, preference: 3 },
  { id: 440, name: "Stir-fried pork with egg & chives (韭黃炒肉絲)", calories: 200, preference: 3 },
  { id: 441, name: "Soupy rice (滑飯)", calories: 150, preference: 3 },
  { id: 442, name: "Stir-fried chicken with lemongrass (香茅雞)", calories: 300, preference: 3 },
  { id: 443, name: "Beef bone soup (clear)", calories: 150, preference: 3 },
  { id: 444, name: "Steamed minced fish cake (蒸魚餅)", calories: 150, preference: 3 },
  { id: 445, name: "Hot pot vegetable soup (時蔬鍋)", calories: 100, preference: 3 },
  { id: 446, name: "Steamed okra", calories: 50, preference: 3 },
  { id: 447, name: "Stir-fried garden peas (炒碗豆)", calories: 150, preference: 3 },
  { id: 448, name: "Stir-fried black fungus (炒木耳)", calories: 100, preference: 3 },
  { id: 449, name: "Boiled broccoli (no sauce)", calories: 50, preference: 3 },
  { id: 450, name: "Boiled baby bok choy (白灼小白菜)", calories: 50, preference: 3 },
  { id: 451, name: "Salted egg fried squid (咸蛋魷魚)", calories: 350, preference: 3 },
  { id: 452, name: "Steamed pumpkin (白灼南瓜)", calories: 50, preference: 3 },
  { id: 453, name: "Stir-fried tofu with chili (辣子豆腐)", calories: 300, preference: 3 },
  { id: 454, name: "Mixed nut brittle (堅果糖)", calories: 200, preference: 3 },
  { id: 455, name: "Turnip puff pastry (蘿蔔酥餅)", calories: 210, preference: 3 },
  { id: 456, name: "Barbecue pork rice (叉燒飯)", calories: 500, preference: 3 },
  { id: 457, name: "Sweet and sour chicken wings (甘梅雞)", calories: 300, preference: 3 },
  { id: 458, name: "Steamed meatball (pork) (豬肉丸)", calories: 150, preference: 3 },
  { id: 459, name: "Steamed fish fillet (蒸魚片)", calories: 150, preference: 3 },
  { id: 460, name: "Carrot cake (vegetarian) (蘿蔔糕 (素))", calories: 170, preference: 3 },
  { id: 461, name: "Sweet lotus root soup (蓮藕糖水)", calories: 100, preference: 3 },
  { id: 462, name: "Chinese lemon tea (without sugar) (檸檬茶 (無糖))", calories: 5, preference: 3 },
  { id: 463, name: "Chinese milk tea (without sugar) (奶茶 (無糖))", calories: 5, preference: 3 },
  { id: 464, name: "Stir-fried soft tofu (燴豆腐)", calories: 150, preference: 3 },
  { id: 465, name: "Stir-fried snow pea sprouts (炒豆苗)", calories: 150, preference: 3 },
  { id: 466, name: "Sweet and sour fish (糖醋魚)", calories: 400, preference: 3 },
  { id: 467, name: "Lemongrass beef (香茅牛肉)", calories: 350, preference: 3 },
  { id: 468, name: "Fried red bean balls (炸紅豆餅)", calories: 200, preference: 3 },
  { id: 469, name: "Deep-fried taro dumpling (芋角)", calories: 150, preference: 3 },
  { id: 470, name: "Ham & egg instant noodles (餐蛋公仔麵)", calories: 750, preference: 3 },
  { id: 471, name: "Hungarian egg waffles (雞蛋仔 (葡撻卷))", calories: 330, preference: 3 },
  { id: 472, name: "Grilled squid (烤魷魚)", calories: 300, preference: 3 },
  { id: 473, name: "Cinnamon roll", calories: 300, preference: 3 },
  { id: 474, name: "Mushroom & vegetable stew", calories: 200, preference: 3 },
  { id: 475, name: "Stir-fried Chinese yam with eggs (炒山藥)", calories: 150, preference: 3 },
  { id: 476, name: "Steamed broccoli (no sauce)", calories: 50, preference: 3 },
  { id: 477, name: "Salt & pepper tofu cubes (椒鹽豆腐塊)", calories: 250, preference: 3 },
  { id: 478, name: "Sweet peanut soup (花生糖水)", calories: 150, preference: 3 },
  { id: 479, name: "Dried squid snack (魷魚絲)", calories: 200, preference: 3 },
  { id: 480, name: "Vegetarian luncheon meat fried rice (素午餐肉炒飯)", calories: 600, preference: 3 },
  { id: 481, name: "Longans & pork ribs soup (桂圓排骨湯)", calories: 120, preference: 3 },
  { id: 482, name: "Steamed rice dumpling with egg yolk (蛋黃糯米糍)", calories: 300, preference: 3 },
  { id: 483, name: "Deep-fried yam ball (芋頭球)", calories: 150, preference: 3 },
  { id: 484, name: "Guangdong-style noodle soup (廣東艇仔粥)", calories: 200, preference: 3 },
  { id: 485, name: "Guangdong-style congee (廣東粥)", calories: 180, preference: 3 },
  { id: 486, name: "Egg noodle soup with shrimp (蝦湯撈麵)", calories: 350, preference: 3 },
  { id: 487, name: "Steamed scallion buns (蔥油卷)", calories: 150, preference: 3 },
  { id: 488, name: "Pan-fried turnip cake (煎蘿蔔糕)", calories: 180, preference: 3 },
  { id: 489, name: "Hong Kong-style macaroni (港式通粉)", calories: 400, preference: 3 },
  { id: 490, name: "Seasoned chicken wing (五香雞翼)", calories: 180, preference: 3 },
  { id: 491, name: "Steamed beef with tofu (豆腐蒸牛肉)", calories: 200, preference: 3 },
  { id: 492, name: "Skewered yakitori (chicken)", calories: 150, preference: 3 },
  { id: 493, name: "Beef brisket & tendon soup (牛腩牛筋湯)", calories: 500, preference: 3 },
  { id: 494, name: "Beef brisket & radish soup (牛腩蘿蔔湯)", calories: 500, preference: 3 },
  { id: 495, name: "Breakfast noodle soup (早餐麵)", calories: 300, preference: 3 },
  { id: 496, name: "Hong Kong fish soup", calories: 150, preference: 3 },
  { id: 497, name: "Roasted pepper steak", calories: 400, preference: 3 },
  { id: 498, name: "Beef pot pie", calories: 600, preference: 3 },
  { id: 499, name: "Lemon chicken wings", calories: 250, preference: 3 },
  { id: 500, name: "Scrambled egg on buttered toast (炒蛋牛油多士)", calories: 400, preference: 3 }
];